# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'inke' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for inke
#网络请求库
pod 'AFNetworking', '~> 3.1.0'
#图片加载库
pod 'SDWebImage', '~> 4.1.0'
#自适应库
pod 'Masonry', '~> 1.0.2'
#YYKit 是一组庞大、功能丰富的 iOS 组件，为什么不用YYImage替代SDWebImage
pod 'YYKit', '~> 1.0.9'
#数据解析，可以处理驼峰，下划线命名
pod 'MJExtension'
end
